const paths=['programs','providers','relations','events','evidence'];
const data=Object.fromEntries(await Promise.all(paths.map(async p=>[p,await fetch(`./data/${p}.json`).then(r=>r.json())])));
const entities=[...data.programs.map(x=>({...x,kind:'program'})),...data.providers.map(x=>({...x,kind:x.provider_types?.includes('network')?'network':'provider'}))];
const byId=new Map(entities.map(x=>[x.id,x]));
const evidenceById=new Map(data.evidence.map(x=>[x.id,x]));
const graph=document.querySelector('#graph'),nodesEl=document.querySelector('#nodes'),svg=document.querySelector('#edges'),trace=document.querySelector('#trace'),evidenceEl=document.querySelector('#evidence'),incidentWindow=document.querySelector('#incident-window');
let focus=data.providers.find(x=>x.slug==='rain')?.id||data.programs[0]?.id;let filter='all',query='',selectedRelation=null;
const incidentTypes=new Set(['vulnerability_discovered','exploit','unauthorized_withdrawal','card_service_suspended','regulatory_action']);
const remediationTypes=new Set(['contract_upgraded','reimbursement_announced','reimbursement_completed','forensic_investigation','confirmed_unaffected']);
const affectedTypes=new Set(['exploit','unauthorized_withdrawal']);
const vulnerableTypes=new Set(['vulnerability_discovered']);
const unaffectedTypes=new Set(['confirmed_unaffected']);
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot',"'":'&#39;'}[c]));
function neighborhood(id){const rels=data.relations.filter(r=>r.from_id===id||r.to_id===id);const ids=new Set([id]);rels.forEach(r=>{ids.add(r.from_id);ids.add(r.to_id)});return {rels,items:[...ids].map(x=>byId.get(x)).filter(Boolean)}}
function impactState(id){const own=data.events.filter(e=>e.entity_id===id);if(own.some(e=>affectedTypes.has(e.event_type)))return{key:'affected',label:'affected'};if(own.some(e=>unaffectedTypes.has(e.event_type)))return{key:'unaffected',label:'confirmed unaffected'};if(own.some(e=>vulnerableTypes.has(e.event_type)))return{key:'vulnerable',label:'provider vulnerability'};return null}
function slugRoute(x){return x?`#/${x.kind}/${encodeURIComponent(x.slug)}`:'#/'}
function setFocus(id,{route=true,dialog=false}={}){if(!byId.has(id))return;focus=id;selectedRelation=null;if(route){const x=byId.get(id);history.replaceState(null,'',slugRoute(x))}renderAll();if(dialog)showEntity(byId.get(id))}
function applyRoute(){const m=location.hash.match(/^#\/(program|provider|network)\/([^/?#]+)/);if(!m)return;const slug=decodeURIComponent(m[2]);const x=entities.find(e=>e.slug===slug);if(x)focus=x.id}
function layout(items,centerId,w,h){const center=items.find(x=>x.id===centerId)||items[0];if(!center)return new Map();const others=items.filter(x=>x!==center);const pos=new Map([[center.id,{x:w/2,y:h/2}]]);others.forEach((x,i)=>{const a=(Math.PI*2*i/Math.max(others.length,1))-Math.PI/2;const rx=Math.min(w*.36,430),ry=Math.min(h*.34,180);pos.set(x.id,{x:w/2+Math.cos(a)*rx,y:h/2+Math.sin(a)*ry})});return pos}
function selectRelation(r){selectedRelation=r.id;renderGraph();showEvidence(r.evidence_ids);const a=byId.get(r.from_id),b=byId.get(r.to_id);document.querySelector('#focus-strip').innerHTML=`Path <strong>${esc(a?.canonical_name||r.from_id)}</strong> <span class="path-arrow">→ ${esc(r.relation_type)} →</span> <strong>${esc(b?.canonical_name||r.to_id)}</strong> · evidence highlighted below.`;document.querySelector('#evidence-path').scrollIntoView({behavior:'smooth',block:'start'})}
function renderGraph(){const {rels,items}=neighborhood(focus);const visible=query?items.filter(x=>x.canonical_name.toLowerCase().includes(query)||x.summary?.toLowerCase().includes(query)):items;const visibleIds=new Set(visible.map(x=>x.id));const rect=graph.getBoundingClientRect(),pos=layout(visible,focus,rect.width,rect.height);nodesEl.innerHTML='';svg.innerHTML='';document.querySelector('#empty').hidden=!!visible.length;
 rels.filter(r=>visibleIds.has(r.from_id)&&visibleIds.has(r.to_id)).forEach(r=>{const a=pos.get(r.from_id),b=pos.get(r.to_id);if(!a||!b)return;const line=document.createElementNS('http://www.w3.org/2000/svg','line');line.setAttribute('x1',a.x);line.setAttribute('y1',a.y);line.setAttribute('x2',b.x);line.setAttribute('y2',b.y);line.setAttribute('class',`edge ${selectedRelation===r.id?'active':''}`);line.dataset.id=r.id;line.tabIndex=0;line.setAttribute('role','button');line.setAttribute('aria-label',`${byId.get(r.from_id)?.canonical_name||r.from_id} ${r.relation_type} ${byId.get(r.to_id)?.canonical_name||r.to_id}`);line.addEventListener('click',()=>selectRelation(r));line.addEventListener('keydown',k=>{if(k.key==='Enter'||k.key===' '){k.preventDefault();selectRelation(r)}});svg.append(line);const t=document.createElementNS('http://www.w3.org/2000/svg','text');t.setAttribute('x',(a.x+b.x)/2);t.setAttribute('y',(a.y+b.y)/2-7);t.setAttribute('class',`edge-label ${selectedRelation===r.id?'active':''}`);t.textContent=r.relation_type;svg.append(t)});
 visible.forEach(x=>{const p=pos.get(x.id);if(!p)return;const impact=impactState(x.id);const connected=selectedRelation&&rels.find(r=>r.id===selectedRelation&&(r.from_id===x.id||r.to_id===x.id));const b=document.createElement('button');b.className=`node ${x.kind} ${impact?`impact-${impact.key}`:''} ${x.id===focus?'center active':''} ${connected?'path-node':''}`;b.style.left=`${p.x}px`;b.style.top=`${p.y}px`;b.innerHTML=`<span class="type">${esc(x.kind)}</span><strong>${esc(x.canonical_name)}</strong><span class="status">${esc(x.status)}</span>${impact?`<span class="impact-badge">${esc(impact.label)}</span>`:''}`;b.onclick=()=>setFocus(x.id,{route:true,dialog:true});nodesEl.append(b)});
 const f=byId.get(focus),impact=impactState(focus);document.querySelector('#focus-label').textContent=f?f.canonical_name:'Relationship field';if(!selectedRelation)document.querySelector('#focus-strip').innerHTML=f?`Focused on <strong>${esc(f.canonical_name)}</strong> · ${rels.length} evidenced relationship${rels.length===1?'':'s'}${impact?` · <span class="focus-impact ${impact.key}">${esc(impact.label)}</span>`:''} · select an edge to illuminate its evidence path.`:'';renderIncidentWindow()}
function relevantEvents(){const n=neighborhood(focus);const ids=new Set(n.items.map(x=>x.id));return data.events.filter(e=>ids.has(e.entity_id)).sort((a,b)=>String(a.event_date).localeCompare(String(b.event_date)))}
function eventClass(e){if(incidentTypes.has(e.event_type))return'incident';if(remediationTypes.has(e.event_type))return'remediation';return'change'}
function renderIncidentWindow(){const events=relevantEvents().filter(e=>incidentTypes.has(e.event_type)||remediationTypes.has(e.event_type));if(!events.length){incidentWindow.hidden=true;incidentWindow.innerHTML='';return}const dates=events.map(e=>e.event_date).filter(Boolean).sort();const first=dates[0]||'date unknown',last=dates.at(-1)||first;incidentWindow.hidden=false;incidentWindow.innerHTML=`<span>INCIDENT WINDOW</span><strong>${esc(first)}${last!==first?` → ${esc(last)}`:''}</strong><small>${events.length} material incident/remediation event${events.length===1?'':'s'} in this neighborhood</small>`}
function renderTrace(){let events=relevantEvents();if(filter!=='all')events=events.filter(e=>eventClass(e)===filter);trace.innerHTML=events.length?'':'<p class="hint">No canonical events in this view.</p>';events.forEach(e=>{const el=document.createElement('article');el.className=`event ${eventClass(e)}`;el.tabIndex=0;el.setAttribute('role','button');el.innerHTML=`<time>${esc(e.event_date||'date unknown')}</time><strong>${esc(e.title)}</strong><small>${esc(byId.get(e.entity_id)?.canonical_name||e.event_type)}</small>`;const action=()=>{showEvidence(e.evidence_ids);setFocus(e.entity_id,{route:true});document.querySelector('#evidence-path').scrollIntoView({behavior:'smooth',block:'start'})};el.onclick=action;el.onkeydown=k=>{if(k.key==='Enter'||k.key===' '){k.preventDefault();action()}};trace.append(el)});document.querySelector('#trace-title').textContent=`${byId.get(focus)?.canonical_name||'Registry'} · material changes`}
function showEvidence(ids=[]){const rows=ids.map(id=>evidenceById.get(id)).filter(Boolean);evidenceEl.innerHTML=rows.length?'':'<p>No linked canonical evidence for this selection.</p>';rows.forEach(e=>{const c=document.createElement('article');c.className='evidence-card';c.innerHTML=`<div class="meta">${esc(e.source_type)} · ${esc(e.publisher)} · ${esc(e.published_at||'undated')}</div><h3>${esc(e.title)}</h3><p>${esc(e.claim_scope)}</p><div class="meta">Reliability: ${esc(e.reliability)}</div><p><a href="${esc(e.url)}" target="_blank" rel="noopener noreferrer">Open source ↗</a></p>`;evidenceEl.append(c)})}
function showEntity(x){const d=document.querySelector('#entity-dialog'),rels=data.relations.filter(r=>r.from_id===x.id||r.to_id===x.id),events=data.events.filter(e=>e.entity_id===x.id),impact=impactState(x.id);document.querySelector('#entity-detail').innerHTML=`<p class="eyebrow">${esc(x.kind)} FOCUS</p><h2>${esc(x.canonical_name)}</h2>${impact?`<p class="entity-impact ${impact.key}">${esc(impact.label)}</p>`:''}<p>${esc(x.summary)}</p><div class="detail-grid"><div><small>Status</small>${esc(x.status)}</div><div><small>Confidence</small>${esc(x.confidence)}</div><div><small>Relationships</small>${rels.length}</div><div><small>Events</small>${events.length}</div><div><small>Last verified</small>${esc(x.last_verified_at)}</div><div><small>Permalink</small><a href="${esc(slugRoute(x))}">Open focus route ↗</a></div><div><small>Official</small><a href="${esc(x.official_url)}" target="_blank" rel="noopener noreferrer">Source ↗</a></div></div>`;d.showModal()}
function renderAll(){renderGraph();renderTrace();const own=data.events.filter(e=>e.entity_id===focus).flatMap(e=>e.evidence_ids||[]);const rel=data.relations.filter(r=>r.from_id===focus||r.to_id===focus).flatMap(r=>r.evidence_ids||[]);showEvidence([...new Set([...own,...rel])].slice(0,6))}
applyRoute();document.querySelector('#search').addEventListener('input',e=>{query=e.target.value.trim().toLowerCase();if(query){const hit=entities.find(x=>x.canonical_name.toLowerCase().includes(query));if(hit)setFocus(hit.id,{route:true});else renderGraph()}else renderAll()});document.querySelectorAll('#filters button').forEach(b=>b.onclick=()=>{document.querySelectorAll('#filters button').forEach(x=>x.classList.remove('active'));b.classList.add('active');filter=b.dataset.filter;renderTrace()});document.querySelector('#entity-dialog .close').onclick=()=>document.querySelector('#entity-dialog').close();document.querySelector('[data-view="graph"]').onclick=()=>graph.scrollIntoView({behavior:'smooth',block:'center'});document.querySelector('[data-view="timeline"]').onclick=()=>document.querySelector('#history').scrollIntoView({behavior:'smooth'});window.addEventListener('resize',()=>renderGraph());window.addEventListener('hashchange',()=>{applyRoute();renderAll()});renderAll();
