const paths=['programs','providers','relations','events','evidence'];
const data=Object.fromEntries(await Promise.all(paths.map(async p=>[p,await fetch(`./data/${p}.json`).then(r=>r.json())])));
const entities=[...data.programs.map(x=>({...x,kind:'program'})),...data.providers.map(x=>({...x,kind:x.provider_types?.includes('network')?'network':'provider'}))];
const byId=new Map(entities.map(x=>[x.id,x]));
const evidenceById=new Map(data.evidence.map(x=>[x.id,x]));
const relationById=new Map(data.relations.map(x=>[x.id,x]));
const isProgram=id=>id?.startsWith('ccr_program_');
const isProvider=id=>id?.startsWith('ccr_provider_');
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const relationName=type=>({uses_provider:'provider',issued_by:'issuer',processed_by:'processor',uses_network:'network',networked_by:'network',settled_by:'settlement',custodied_by:'custody',program_managed_by:'program manager',program_manager:'program manager',collateral_contract:'collateral contract',migrated_to:'migrated to'})[type]||String(type||'relationship').replaceAll('_',' ');
const incidentTypes=new Set(['vulnerability_discovered','exploit','unauthorized_withdrawal','card_service_suspended','regulatory_action']);
const remediationTypes=new Set(['contract_upgraded','reimbursement_announced','reimbursement_completed','forensic_investigation','confirmed_unaffected']);
const panels={overview:document.querySelector('#panel-overview'),explore:document.querySelector('#panel-explore'),history:document.querySelector('#panel-history'),incidents:document.querySelector('#panel-incidents')};
const nav=[...document.querySelectorAll('[data-route]')];
const globalSearch=document.querySelector('#search');
const searchResults=document.querySelector('#search-results');
const overviewInspector=document.querySelector('#overview-inspector');
const overviewSources=document.querySelector('#overview-sources');
const exploreGraph=document.querySelector('#focus-graph');
const exploreSvg=document.querySelector('#focus-edges');
const exploreNodes=document.querySelector('#focus-nodes');
const exploreInspector=document.querySelector('#explore-inspector');
const exploreTitle=document.querySelector('#explore-title');
const explorePager=document.querySelector('#explore-pager');
const historyList=document.querySelector('#history-list');
const historyDrawer=document.querySelector('#history-drawer');
const incidentList=document.querySelector('#incident-list');
const incidentDrawer=document.querySelector('#incident-drawer');
const state={mode:'overview',overviewProviderId:null,overviewPage:0,exploreRootId:null,explorePage:0,expandedProgramId:null,selectedRelationId:null,historyFilter:'all',historyEventId:null,incidentEventId:null};
const PAGE=6,GRAPH_PAGE=8;
function relationsFor(id){return data.relations.filter(r=>r.from_id===id||r.to_id===id)}
function relatedPrograms(id){return[...new Set(relationsFor(id).flatMap(r=>[r.from_id,r.to_id].filter(isProgram)))]}
function providerRelationsForProgram(id){return relationsFor(id).map(r=>{const providerId=isProvider(r.from_id)?r.from_id:isProvider(r.to_id)?r.to_id:null;return providerId?{...r,providerId,provider:byId.get(providerId)}:null}).filter(x=>x?.provider)}
function providerEvents(id){return data.events.filter(e=>e.entity_id===id)}
function routeForEntity(x){if(!x)return'#/explore';return`#/explore/${x.kind}/${encodeURIComponent(x.slug)}`}
function eventClass(e){if(incidentTypes.has(e.event_type))return'incident';if(remediationTypes.has(e.event_type))return'remediation';return'change'}
function evidenceRows(ids=[]){return ids.map(id=>evidenceById.get(id)).filter(Boolean)}
function entityEventCount(id){return data.events.filter(e=>e.entity_id===id).length}
function normalizeInitialUrl(){const originalHash=location.hash;let hash=originalHash==='#/overview'?'':originalHash;const cleanPath=location.pathname.endsWith('/index.html')?location.pathname.slice(0,-'index.html'.length):location.pathname;if(cleanPath!==location.pathname||hash!==originalHash)history.replaceState(null,'',`${cleanPath}${location.search}${hash}`)}
function parseRoute(){const h=location.hash;if(!h)return{mode:'overview'};if(h==='#/history'||h.startsWith('#/history?'))return{mode:'history'};if(h==='#/incidents'||h.startsWith('#/incidents?'))return{mode:'incidents'};if(h==='#/explore')return{mode:'explore'};let m=h.match(/^#\/explore\/(program|provider|network)\/([^/?#]+)/);if(!m){const legacy=h.match(/^#\/(program|provider|network)\/([^/?#]+)/);if(legacy){const target=`#/explore/${legacy[1]}/${legacy[2]}`;history.replaceState(null,'',`${location.pathname}${location.search}${target}`);m=target.match(/^#\/explore\/(program|provider|network)\/([^/?#]+)/)}}if(m){const x=entities.find(e=>e.kind===m[1]&&e.slug===decodeURIComponent(m[2]));return{mode:'explore',entity:x||null}}return{mode:'overview'}}
function applyRoute(){const route=parseRoute();state.mode=route.mode;if(route.mode==='explore'){state.exploreRootId=route.entity?.id||null;state.explorePage=0;state.expandedProgramId=null;state.selectedRelationId=null}Object.entries(panels).forEach(([name,panel])=>panel?.toggleAttribute('hidden',name!==state.mode));document.body.dataset.mode=state.mode;nav.forEach(el=>el.classList.toggle('active',el.dataset.route===state.mode));if(state.mode==='overview')renderOverview();if(state.mode==='explore')renderExplore();if(state.mode==='history')renderHistory();if(state.mode==='incidents')renderIncidents()}
function navigate(mode){if(mode==='overview'){history.pushState(null,'',`${location.pathname.replace(/index\.html$/,'')}${location.search}`);applyRoute()}else location.hash=`#/${mode}`}
function renderMetrics(){const target=document.querySelector('#overview-metrics');if(!target)return;const rows=[[data.programs.length,'Programs'],[data.providers.length,'Providers'],[data.relations.length,'Relationships'],[data.events.length,'Lifecycle events']];target.innerHTML=rows.map(([value,label])=>`<article><strong>${value}</strong><span>${label}</span></article>`).join('')}
function networkRows(){return data.providers.filter(p=>p.provider_types?.includes('network')).map(provider=>({provider,count:relatedPrograms(provider.id).length})).filter(x=>x.count).sort((a,b)=>b.count-a.count)}
function hubRows(){return data.providers.filter(p=>!p.provider_types?.includes('network')).map(provider=>({provider,count:relatedPrograms(provider.id).length,events:providerEvents(provider.id).length})).filter(x=>x.count).sort((a,b)=>b.count-a.count||b.events-a.events)}
function renderOverviewSources(){if(!overviewSources)return;const networks=networkRows(),hubs=hubRows().slice(0,12),max=Math.max(1,...networks.map(x=>x.count));overviewSources.innerHTML=`<div class="master-group"><div class="master-head"><span>NETWORKS</span><small>Programs with an evidenced network relation</small></div>${networks.map(({provider,count})=>`<button class="master-row ${state.overviewProviderId===provider.id?'active':''}" data-overview-provider="${provider.id}"><span><b>${esc(provider.canonical_name)}</b><small>${count} programs</small></span><em><i style="width:${Math.max(7,Math.round(count/max*100))}%"></i></em><strong>${count}</strong></button>`).join('')}</div><div class="master-group"><div class="master-head"><span>INFRASTRUCTURE</span><small>Most shared reviewed dependencies</small></div>${hubs.map(({provider,count})=>`<button class="master-row compact ${state.overviewProviderId===provider.id?'active':''}" data-overview-provider="${provider.id}"><span><b>${esc(provider.canonical_name)}</b><small>${esc((provider.provider_types||[]).join(' · ')||'provider')}</small></span><strong>${count}</strong></button>`).join('')}</div>`}
function sharedDependencies(programIds,selectedId){const counts=new Map();programIds.forEach(id=>providerRelationsForProgram(id).forEach(rel=>{if(rel.providerId===selectedId)return;const cur=counts.get(rel.providerId)||{provider:rel.provider,count:0};cur.count++;counts.set(rel.providerId,cur)}));return[...counts.values()].sort((a,b)=>b.count-a.count||a.provider.canonical_name.localeCompare(b.provider.canonical_name)).slice(0,6)}
function renderOverviewInspector(){if(!overviewInspector)return;if(!state.overviewProviderId){const initial=networkRows()[0]?.provider||hubRows()[0]?.provider;if(initial)state.overviewProviderId=initial.id}const provider=byId.get(state.overviewProviderId);if(!provider){overviewInspector.innerHTML='<div class="empty-panel">Select a network or infrastructure provider.</div>';return}const programIds=relatedPrograms(provider.id),programs=programIds.map(id=>byId.get(id)).filter(Boolean).sort((a,b)=>a.canonical_name.localeCompare(b.canonical_name)),pages=Math.max(1,Math.ceil(programs.length/PAGE));state.overviewPage=Math.min(state.overviewPage,pages-1);const start=state.overviewPage*PAGE,shown=programs.slice(start,start+PAGE),shared=sharedDependencies(programIds,provider.id),eventCount=providerEvents(provider.id).length;overviewInspector.innerHTML=`<div class="inspector-head"><div><span class="panel-kicker">CONNECTION INSPECTOR</span><h2>${esc(provider.canonical_name)}</h2><p>${programs.length} connected program${programs.length===1?'':'s'} · ${eventCount} provider-owned event${eventCount===1?'':'s'}</p></div><a class="explicit-link" href="${routeForEntity(provider)}">Inspect in Explore →</a></div><div class="inspector-programs">${shown.map(program=>{const deps=providerRelationsForProgram(program.id).filter(r=>r.providerId!==provider.id);return`<article class="program-card"><div class="program-card-head"><div><strong>${esc(program.canonical_name)}</strong><small>${esc(program.status||'unknown')}</small></div><a href="${routeForEntity(program)}">Open program ↗</a></div><div class="program-deps"><span class="origin-dep">${esc(provider.canonical_name)}</span>${deps.slice(0,4).map(r=>`<span><small>${esc(relationName(r.relation_type))}</small>${esc(r.provider.canonical_name)}</span>`).join('')}${deps.length>4?`<em>+${deps.length-4} more</em>`:''}</div></article>`}).join('')}</div><div class="inspector-footer"><div class="pager"><button data-overview-prev ${state.overviewPage===0?'disabled':''}>← Previous</button><span>${programs.length?start+1:0}–${Math.min(start+PAGE,programs.length)} of ${programs.length}</span><button data-overview-next ${state.overviewPage>=pages-1?'disabled':''}>Next →</button></div><div class="shared-box"><span>SHARED DEPENDENCIES</span>${shared.length?shared.map(x=>`<div><b>${esc(x.provider.canonical_name)}</b><em>${x.count}/${programs.length}</em><i><u style="width:${programs.length?Math.round(x.count/programs.length*100):0}%"></u></i></div>`).join(''):'<small>No repeated co-dependency in this set.</small>'}</div></div>`}
function renderOverview(){renderMetrics();renderOverviewSources();renderOverviewInspector()}
function quickEntityIds(){return['Visa','Mastercard','Rain','Third National'].map(name=>entities.find(x=>x.canonical_name===name)?.id).filter(Boolean)}
function renderExploreEmpty(){exploreTitle.textContent='Explore relationships';exploreGraph.hidden=true;explorePager.innerHTML='';exploreInspector.innerHTML=`<div class="explore-empty"><span class="panel-kicker">FOCUS GRAPH</span><h2>Choose one entity to start.</h2><p>The graph never loads the whole registry at once. Start with a program, network or provider and inspect one hop at a time.</p><div class="quick-picks">${quickEntityIds().map(id=>{const x=byId.get(id);return`<a href="${routeForEntity(x)}">${esc(x.canonical_name)}</a>`}).join('')}</div></div>`}
function rootNeighbors(root){const rows=relationsFor(root.id).map(r=>{const otherId=r.from_id===root.id?r.to_id:r.from_id;return{relation:r,entity:byId.get(otherId)}}).filter(x=>x.entity);if(root.kind!=='program')return rows.filter(x=>x.entity.kind==='program').sort((a,b)=>a.entity.canonical_name.localeCompare(b.entity.canonical_name));return rows.sort((a,b)=>a.entity.kind.localeCompare(b.entity.kind)||a.entity.canonical_name.localeCompare(b.entity.canonical_name))}
function drawEdge(a,b,relation,active=false){const line=document.createElementNS('http://www.w3.org/2000/svg','line');line.setAttribute('x1',a.x);line.setAttribute('y1',a.y);line.setAttribute('x2',b.x);line.setAttribute('y2',b.y);line.setAttribute('class',`focus-edge ${active?'active':''}`);line.dataset.relationId=relation.id;line.tabIndex=0;line.setAttribute('role','button');line.setAttribute('aria-label',`${relationName(relation.relation_type)} connection`);line.addEventListener('click',()=>{state.selectedRelationId=relation.id;renderExploreInspector();renderExploreGraph()});line.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();line.click()}});exploreSvg.append(line)}
function addNode(entity,x,y,{root=false,expanded=false}={}){const btn=document.createElement('button');btn.className=`focus-node ${entity.kind} ${root?'root':''} ${expanded?'expanded':''}`;btn.style.left=`${x}px`;btn.style.top=`${y}px`;btn.dataset.entityId=entity.id;btn.innerHTML=`<span>${esc(entity.kind)}</span><strong>${esc(entity.canonical_name)}</strong><small>${esc(entity.status||'unknown')}</small>${entityEventCount(entity.id)?`<em>${entityEventCount(entity.id)} event${entityEventCount(entity.id)===1?'':'s'}</em>`:''}`;exploreNodes.append(btn);return btn}
function renderExploreGraph(){const root=byId.get(state.exploreRootId);if(!root){renderExploreEmpty();return}exploreGraph.hidden=false;exploreTitle.textContent=root.canonical_name;exploreSvg.innerHTML='';exploreNodes.innerHTML='';const rect=exploreGraph.getBoundingClientRect(),w=Math.max(760,rect.width||1000),h=Math.max(520,rect.height||620);exploreSvg.setAttribute('viewBox',`0 0 ${w} ${h}`);const neighbors=rootNeighbors(root),pages=Math.max(1,Math.ceil(neighbors.length/GRAPH_PAGE));state.explorePage=Math.min(state.explorePage,pages-1);const visible=neighbors.slice(state.explorePage*GRAPH_PAGE,state.explorePage*GRAPH_PAGE+GRAPH_PAGE),rootPos=root.kind==='program'?{x:w*.28,y:h*.5}:{x:w*.16,y:h*.5};addNode(root,rootPos.x,rootPos.y,{root:true});const positions=new Map([[root.id,rootPos]]);if(root.kind==='program'){visible.forEach((row,i)=>{const y=h*(i+1)/(visible.length+1),pos={x:w*.68,y};positions.set(row.entity.id,pos);addNode(row.entity,pos.x,pos.y);drawEdge(rootPos,pos,row.relation,state.selectedRelationId===row.relation.id)})}else{visible.forEach((row,i)=>{const y=h*(i+1)/(visible.length+1),pos={x:w*.46,y};positions.set(row.entity.id,pos);addNode(row.entity,pos.x,pos.y,{expanded:row.entity.id===state.expandedProgramId});drawEdge(rootPos,pos,row.relation,state.selectedRelationId===row.relation.id)});const expanded=byId.get(state.expandedProgramId);if(expanded&&visible.some(r=>r.entity.id===expanded.id)){const origin=positions.get(expanded.id),deps=providerRelationsForProgram(expanded.id).filter(r=>r.providerId!==root.id).slice(0,6);deps.forEach((rel,i)=>{const spread=Math.min(h*.72,Math.max(150,deps.length*72)),start=Math.max(45,origin.y-spread/2),y=Math.min(h-45,start+(i+.5)*spread/Math.max(1,deps.length)),pos={x:w*.82,y};addNode(rel.provider,pos.x,pos.y);drawEdge(origin,pos,rel,state.selectedRelationId===rel.id)})}}explorePager.innerHTML=`<button data-explore-prev ${state.explorePage===0?'disabled':''}>← Previous</button><span>${neighbors.length?state.explorePage*GRAPH_PAGE+1:0}–${Math.min((state.explorePage+1)*GRAPH_PAGE,neighbors.length)} of ${neighbors.length} direct connection${neighbors.length===1?'':'s'}</span><button data-explore-next ${state.explorePage>=pages-1?'disabled':''}>Next →</button>`}
function renderExploreInspector(){const root=byId.get(state.exploreRootId);if(!root){renderExploreEmpty();return}const selected=relationById.get(state.selectedRelationId);if(selected){const a=byId.get(selected.from_id),b=byId.get(selected.to_id),rows=evidenceRows(selected.evidence_ids);exploreInspector.innerHTML=`<div class="drawer-head"><span class="panel-kicker">RELATIONSHIP</span><h3>${esc(a?.canonical_name||selected.from_id)} → ${esc(b?.canonical_name||selected.to_id)}</h3><p>${esc(relationName(selected.relation_type))}${selected.jurisdiction_scope?.length?` · ${esc(selected.jurisdiction_scope.join(', '))}`:''}</p></div>${selected.scope_note?`<p class="drawer-note">${esc(selected.scope_note)}</p>`:''}<div class="evidence-stack">${rows.map(evidenceCard).join('')||'<p class="muted">No linked evidence.</p>'}</div><button class="drawer-clear" data-clear-relation>Back to entity summary</button>`;return}const rels=relationsFor(root.id);exploreInspector.innerHTML=`<div class="drawer-head"><span class="panel-kicker">FOCUS</span><h3>${esc(root.canonical_name)}</h3><p>${esc(root.kind)} · ${esc(root.status||'unknown')} · ${rels.length} evidenced relationship${rels.length===1?'':'s'}</p></div><p class="drawer-note">${esc(root.summary||'Select an edge to inspect evidence. If the focus is a shared provider, select one program node to reveal that program’s other dependencies.')}</p><div class="mini-relations">${rels.slice(0,8).map(r=>{const other=byId.get(r.from_id===root.id?r.to_id:r.from_id);return`<button data-inspector-relation="${r.id}"><span>${esc(relationName(r.relation_type))}</span><b>${esc(other?.canonical_name||'Unknown')}</b></button>`}).join('')}</div>`}
function renderExplore(){if(!state.exploreRootId){renderExploreEmpty();return}renderExploreGraph();renderExploreInspector()}
function evidenceCard(e){return`<article class="evidence-mini"><div>${esc(e.source_type)} · ${esc(e.publisher)} · ${esc(e.published_at||'undated')}</div><strong>${esc(e.title)}</strong><p>${esc(e.claim_scope)}</p><a href="${esc(e.url)}" target="_blank" rel="noopener noreferrer">Open source ↗</a></article>`}
function filteredHistoryEvents(){let rows=data.events.slice().sort((a,b)=>String(b.event_date||'').localeCompare(String(a.event_date||'')));if(state.historyFilter==='incident')rows=rows.filter(e=>incidentTypes.has(e.event_type));else if(state.historyFilter==='remediation')rows=rows.filter(e=>remediationTypes.has(e.event_type));else if(state.historyFilter==='launch')rows=rows.filter(e=>String(e.event_type).includes('launch'));else if(state.historyFilter==='shutdown')rows=rows.filter(e=>String(e.event_type).includes('shutdown'));else if(state.historyFilter==='provider-change')rows=rows.filter(e=>String(e.event_type).includes('provider')||String(e.event_type).includes('migration'));return rows}
function renderEventDrawer(target,eventId,mode){const e=data.events.find(x=>x.id===eventId);if(!e){target.innerHTML=`<div class="drawer-empty"><span class="panel-kicker">DETAIL</span><h3>Select an event.</h3><p>Event details and canonical evidence stay here. Nothing changes mode automatically.</p></div>`;return}const entity=byId.get(e.entity_id),rows=evidenceRows(e.evidence_ids);target.innerHTML=`<div class="drawer-head"><span class="panel-kicker">${mode==='incidents'?'INCIDENT / REMEDIATION':'EVENT DETAIL'}</span><h3>${esc(e.title)}</h3><p>${esc(e.event_date||'date unknown')} · ${esc(String(e.event_type).replaceAll('_',' '))}</p></div><div class="event-entity"><span>RELATED ENTITY</span><strong>${esc(entity?.canonical_name||e.entity_id)}</strong><small>${esc(entity?.kind||'entity')}</small></div>${e.summary?`<p class="drawer-note">${esc(e.summary)}</p>`:''}<div class="evidence-stack">${rows.map(evidenceCard).join('')||'<p class="muted">No linked evidence.</p>'}</div>${entity?`<a class="explicit-link full" href="${routeForEntity(entity)}">Open entity in Explore →</a>`:''}`}
function renderHistory(){const rows=filteredHistoryEvents();document.querySelectorAll('[data-history-filter]').forEach(b=>b.classList.toggle('active',b.dataset.historyFilter===state.historyFilter));historyList.innerHTML=rows.map(e=>{const entity=byId.get(e.entity_id);return`<button class="history-row ${state.historyEventId===e.id?'active':''}" data-history-event="${e.id}"><time>${esc(e.event_date||'unknown')}</time><span><strong>${esc(e.title)}</strong><small>${esc(entity?.canonical_name||e.entity_id)} · ${esc(String(e.event_type).replaceAll('_',' '))}</small></span><em class="${eventClass(e)}">${eventClass(e)}</em></button>`}).join('')||'<p class="muted">No canonical events in this filter.</p>';renderEventDrawer(historyDrawer,state.historyEventId,'history')}
function incidentRows(){return data.events.filter(e=>incidentTypes.has(e.event_type)||remediationTypes.has(e.event_type)).sort((a,b)=>String(b.event_date||'').localeCompare(String(a.event_date||'')))}
function renderIncidents(){const rows=incidentRows();incidentList.innerHTML=rows.map(e=>{const entity=byId.get(e.entity_id);return`<button class="incident-row ${state.incidentEventId===e.id?'active':''}" data-incident-event="${e.id}"><span class="incident-mark ${eventClass(e)}"></span><div><time>${esc(e.event_date||'unknown')}</time><strong>${esc(e.title)}</strong><small>${esc(entity?.canonical_name||e.entity_id)} · ${esc(String(e.event_type).replaceAll('_',' '))}</small></div></button>`}).join('');renderEventDrawer(incidentDrawer,state.incidentEventId,'incidents')}
function showSearchResults(value){const q=value.trim().toLowerCase();if(!q){searchResults.hidden=true;searchResults.innerHTML='';return}const hits=entities.filter(x=>x.canonical_name.toLowerCase().includes(q)||x.slug?.includes(q)).slice(0,7);searchResults.innerHTML=hits.length?hits.map(x=>`<a href="${routeForEntity(x)}"><span>${esc(x.kind)}</span><strong>${esc(x.canonical_name)}</strong></a>`).join(''):'<div class="search-empty">No matching canonical entity.</div>';searchResults.hidden=false}
normalizeInitialUrl();
nav.forEach(el=>el.addEventListener('click',e=>{const mode=el.dataset.route;if(!mode)return;if(mode==='overview'){e.preventDefault();navigate('overview')}}));
window.addEventListener('hashchange',applyRoute);window.addEventListener('popstate',applyRoute);
globalSearch?.addEventListener('input',e=>showSearchResults(e.target.value));globalSearch?.addEventListener('keydown',e=>{if(e.key==='Escape'){searchResults.hidden=true;globalSearch.blur()}if(e.key==='Enter'){const first=searchResults.querySelector('a');if(first){location.hash=first.getAttribute('href').slice(1);searchResults.hidden=true;globalSearch.value=''}}});document.addEventListener('click',e=>{if(!e.target.closest('.search-wrap'))searchResults.hidden=true});
overviewSources?.addEventListener('click',e=>{const btn=e.target.closest('[data-overview-provider]');if(!btn)return;state.overviewProviderId=btn.dataset.overviewProvider;state.overviewPage=0;renderOverviewSources();renderOverviewInspector()});overviewInspector?.addEventListener('click',e=>{if(e.target.closest('[data-overview-prev]')){state.overviewPage=Math.max(0,state.overviewPage-1);renderOverviewInspector()}if(e.target.closest('[data-overview-next]')){state.overviewPage++;renderOverviewInspector()}});
document.querySelector('#explore-start-search')?.addEventListener('input',e=>{const q=e.target.value.trim().toLowerCase(),box=document.querySelector('#explore-start-results');if(!q){box.innerHTML='';return}box.innerHTML=entities.filter(x=>x.canonical_name.toLowerCase().includes(q)).slice(0,10).map(x=>`<a href="${routeForEntity(x)}"><span>${esc(x.kind)}</span>${esc(x.canonical_name)}</a>`).join('')});explorePager?.addEventListener('click',e=>{if(e.target.closest('[data-explore-prev]')){state.explorePage=Math.max(0,state.explorePage-1);state.expandedProgramId=null;state.selectedRelationId=null;renderExplore()}if(e.target.closest('[data-explore-next]')){state.explorePage++;state.expandedProgramId=null;state.selectedRelationId=null;renderExplore()}});exploreNodes?.addEventListener('click',e=>{const node=e.target.closest('[data-entity-id]');if(!node)return;const id=node.dataset.entityId,root=byId.get(state.exploreRootId),entity=byId.get(id);if(!root||!entity||id===root.id)return;if(root.kind!=='program'&&entity.kind==='program'){state.expandedProgramId=state.expandedProgramId===id?null:id;state.selectedRelationId=null;renderExploreGraph();renderExploreInspector()}else location.hash=routeForEntity(entity).slice(1)});exploreInspector?.addEventListener('click',e=>{const rel=e.target.closest('[data-inspector-relation]');if(rel){state.selectedRelationId=rel.dataset.inspectorRelation;renderExploreInspector();renderExploreGraph()}if(e.target.closest('[data-clear-relation]')){state.selectedRelationId=null;renderExploreInspector();renderExploreGraph()}});
document.querySelector('#history-filters')?.addEventListener('click',e=>{const b=e.target.closest('[data-history-filter]');if(!b)return;state.historyFilter=b.dataset.historyFilter;state.historyEventId=null;renderHistory()});historyList?.addEventListener('click',e=>{const b=e.target.closest('[data-history-event]');if(!b)return;state.historyEventId=b.dataset.historyEvent;renderHistory()});incidentList?.addEventListener('click',e=>{const b=e.target.closest('[data-incident-event]');if(!b)return;state.incidentEventId=b.dataset.incidentEvent;renderIncidents()});
window.addEventListener('resize',()=>{if(state.mode==='explore'&&state.exploreRootId)renderExploreGraph()});applyRoute();