const detailPaths=['programs','providers','relations','events'];
const detailData=Object.fromEntries(await Promise.all(detailPaths.map(async p=>[p,await fetch(`./data/${p}.json`).then(r=>r.json())])));
const detailEntities=[...detailData.programs.map(x=>({...x,kind:'program'})),...detailData.providers.map(x=>({...x,kind:x.provider_types?.includes('network')?'network':'provider'}))];
const detailById=new Map(detailEntities.map(x=>[x.id,x]));
const detailEsc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const detailRelationName=type=>({uses_provider:'provider',issued_by:'issuer',processed_by:'processor',uses_network:'network',networked_by:'network',settled_by:'settlement',custodied_by:'custody',program_managed_by:'program manager',program_manager:'program manager',collateral_contract:'collateral contract',migrated_to:'migrated to'})[type]||String(type||'relationship').replaceAll('_',' ');
const detailRelationsFor=id=>detailData.relations.filter(r=>r.from_id===id||r.to_id===id);
const detailEventsFor=id=>detailData.events.filter(e=>e.entity_id===id).sort((a,b)=>String(b.event_date||'').localeCompare(String(a.event_date||'')));
const detailRoute=x=>`#/explore/${x.kind}/${encodeURIComponent(x.slug)}`;
function currentRoot(){const m=location.hash.match(/^#\/explore\/(program|provider|network)\/([^/?#]+)/);if(!m)return null;return detailEntities.find(x=>x.kind===m[1]&&x.slug===decodeURIComponent(m[2]))||null}
function detailMetaRow(label,value){if(value===undefined||value===null||value===''||(Array.isArray(value)&&!value.length))return'';const text=Array.isArray(value)?value.join(' · '):value;return`<div><span>${detailEsc(label)}</span><b>${detailEsc(text)}</b></div>`}
function renderEntityDetail(entity){const target=document.querySelector('#explore-inspector');if(!target||!entity)return;const rels=detailRelationsFor(entity.id),events=detailEventsFor(entity.id),root=currentRoot();const relationshipRows=rels.slice(0,8).map(r=>{const otherId=r.from_id===entity.id?r.to_id:r.from_id,other=detailById.get(otherId);return`<div class="entity-detail-relation"><span>${detailEsc(detailRelationName(r.relation_type))}</span><b>${detailEsc(other?.canonical_name||otherId)}</b></div>`}).join('');const recentEvents=events.slice(0,3).map(e=>`<div class="entity-detail-event"><time>${detailEsc(e.event_date||'date unknown')}</time><b>${detailEsc(e.title)}</b></div>`).join('');target.innerHTML=`<div class="drawer-head entity-detail-head"><span class="panel-kicker">ENTITY DETAIL</span><h3>${detailEsc(entity.canonical_name)}</h3><p>${detailEsc(entity.kind)} · ${detailEsc(entity.status||'unknown')}</p></div><p class="drawer-note entity-detail-summary">${detailEsc(entity.summary||'No public summary is recorded for this entity.')}</p><div class="entity-detail-grid">${detailMetaRow('Status',entity.status||'unknown')}${detailMetaRow('Role',entity.provider_types||entity.kind)}${detailMetaRow('Confidence',entity.confidence)}${detailMetaRow('Last verified',entity.last_verified_at)}${detailMetaRow('Relationships',rels.length)}${detailMetaRow('Events',events.length)}</div>${relationshipRows?`<section class="entity-detail-section"><span>CONNECTED TO</span><div class="entity-detail-relations">${relationshipRows}</div></section>`:''}${recentEvents?`<section class="entity-detail-section"><span>RECENT EVENTS</span><div class="entity-detail-events">${recentEvents}</div></section>`:''}<div class="entity-detail-actions">${entity.official_url?`<a class="explicit-link" href="${detailEsc(entity.official_url)}" target="_blank" rel="noopener noreferrer">Official source ↗</a>`:''}${!root||root.id!==entity.id?`<a class="explicit-link" href="${detailRoute(entity)}">Make focus →</a>`:''}</div>`}
const graphNodes=document.querySelector('#focus-nodes');
graphNodes?.addEventListener('click',e=>{const node=e.target.closest('[data-entity-id]');if(!node)return;const entity=detailById.get(node.dataset.entityId),root=currentRoot();if(!entity)return;if(root&&entity.id!==root.id&&entity.kind!=='program'){e.stopPropagation();e.preventDefault();renderEntityDetail(entity);return}requestAnimationFrame(()=>renderEntityDetail(entity))},true);
window.addEventListener('hashchange',()=>{const root=currentRoot();if(root)requestAnimationFrame(()=>renderEntityDetail(root))});
