const publicLabels = new Map([
  ['uses_provider', 'infrastructure'],['issued_by', 'issued by'],['processed_by', 'processed by'],['uses_network', 'card network'],['settled_by', 'settled by'],['custodied_by', 'custody by'],['program_manager', 'program manager'],['collateral_contract', 'collateral contract'],['vulnerability_discovered', 'vulnerability discovered'],['unauthorized_withdrawal', 'unauthorized withdrawal'],['card_service_limited', 'card service limited'],['card_service_suspended', 'card service suspended'],['contract_upgraded', 'contract upgraded'],['reimbursement_announced', 'reimbursement announced'],['reimbursement_completed', 'reimbursement completed'],['forensic_investigation', 'forensic investigation'],['regulatory_action', 'regulatory action'],['confirmed_unaffected', 'confirmed unaffected'],['shutdown_announced', 'shutdown announced'],['shutdown_effective', 'shutdown effective'],['provider_changed', 'provider changed'],['custody_model_changed', 'custody model changed'],['official_documentation', 'official documentation'],['official_statement', 'official statement'],['official_social', 'official social'],['onchain_transaction', 'on-chain transaction'],['independent_forensics', 'independent forensics']
]);
const escapeRegExp=value=>value.replace(/[.*+?^${}()|[\]\\]/g,'\\$&');
const labelPatterns=[...publicLabels].map(([raw,label])=>[new RegExp(`\\b${escapeRegExp(raw)}\\b`,'g'),label]);
function humanizeValue(value){let next=String(value??'');for(const [pattern,label] of labelPatterns)next=next.replace(pattern,label);return next}
function humanizePublicText(){const walker=document.createTreeWalker(document.body,NodeFilter.SHOW_TEXT);const nodes=[];while(walker.nextNode())nodes.push(walker.currentNode);for(const node of nodes){const next=humanizeValue(node.nodeValue);if(next!==node.nodeValue)node.nodeValue=next}document.querySelectorAll('[aria-label],[title]').forEach(element=>{for(const attr of ['aria-label','title']){if(!element.hasAttribute(attr))continue;const current=element.getAttribute(attr);const next=humanizeValue(current);if(next!==current)element.setAttribute(attr,next)}})}
let scheduled=false;function scheduleHumanize(){if(scheduled)return;scheduled=true;requestAnimationFrame(()=>{scheduled=false;humanizePublicText()})}
new MutationObserver(scheduleHumanize).observe(document.body,{subtree:true,childList:true});
scheduleHumanize();
